#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --cpus-per-task=28
#SBATCH --partition=compute
#SBATCH --gpus-per-node=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=64GB
#SBATCH --output=/home/%u/logs/shapenet/%x_%j.out
#SBATCH --nice=0
#SBATCH --array=1-20%5

EXPERIMENT_FILE=tutorial/jobs/experiments/shapenet_experiments.txt
# run
srun --kill-on-bad-exit=1 --cpus-per-task=28 uv run noether-train --hp tutorial/configs/train_shapenet.yaml $(head -$SLURM_ARRAY_TASK_ID $EXPERIMENT_FILE | tail -1) 